nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/":
      allow_methods: ["GET"]
      allow_headers: ["X-Custom-Auth"]
    "^/translate":
      allow_methods: ["OPTIONS", "POST"]
    "^/":
      origin_regex: true
      allow_origin: ["^http://localhost:[0-9]+"]
      allow_headers: ["X-Custom-Auth"]
      allow_methods: ["POST", "PUT", "GET", "DELETE"]
      max_age: 3600
      hosts: ['^api\.']
