version: '3.8'

services:
  app:
    build: .
    container_name: symfony_api
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=your-dev-secret-key-change-this
      - DATABASE_URL=postgresql://symfony:symfony@db:5432/symfony_db
      - CORS_ALLOW_ORIGIN=http://localhost:3000
    volumes:
      - ./:/var/www/symfony:cached
      - symfony_var:/var/www/symfony/var
    depends_on:
      - db
    networks:
      - symfony_network

  db:
    image: postgres:15-alpine
    container_name: symfony_db
    environment:
      - POSTGRES_DB=symfony_db
      - POSTGRES_USER=symfony
      - POSTGRES_PASSWORD=symfony
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony_network

  adminer:
    image: adminer:4.8.1
    container_name: symfony_adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - symfony_network

volumes:
  postgres_data:
  symfony_var:

networks:
  symfony_network:
    driver: bridge