# render.yaml
services:
  - type: web
    env: docker
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration && \
      php bin/console doctrine:fixtures:load --no-interaction --append && \
      php -S 0.0.0.0:8000 -t public
