services:
  - type: web
    name: symfony-api
    runtime: php
    plan: free
    buildCommand: |
      composer require symfony/runtime --no-interaction
      composer install --no-dev --optimize-autoloader
      mkdir -p var/cache var/log var/sessions
      chmod -R 777 var
    startCommand: ./start.sh
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: symfony-db
          property: connectionString
      - key: CORS_ALLOW_ORIGIN
        value: "*"

  - type: pserv
    name: symfony-db
    plan: free