services:
  - type: web
    name: symfony-app
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader && mkdir -p var
    startCommand: ./render-entrypoint.sh
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jokesdb_ql09
          property: connectionString
          
  - type: pserv
    name: jokesdb_ql09
    plan: free