services:
  - type: web
    name: symfony-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        sync: false
    postDeploy:
      - php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
      - php bin/console doctrine:fixtures:load --no-interaction
