services:
  - type: web
    name: symfony-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: symfony-db
          property: connectionString
      - key: CORS_ALLOW_ORIGIN
        value: "*"

  - type: pserv
    name: symfony-db
    plan: free